version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microdb
    ports:
      - "3307:3306"
    networks:
      - mynetwork

  product-ui:
    build:
      context: ./product_management        # directory where your Dockerfile is locateds
      dockerfile: Dockerfile
    container_name: product-ui
    ports:
      - "5173:5173"
    volumes:
      - ./product_management:/product_management        # live sync source code
      - /product_management/node_modules  # avoid overwriting node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped
    networks:
      - mynetwork

  eureka-server:
    build:
      context: ./eureka-server
    image: eureka-server:1.0
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    build:
      context: ./api-gateway
    image: api-gateway:1.0
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  user-service:
    build:
      context: ./user-service
    image: user-service:1.0
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microdb?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  product-service:
    build:
      context: ./product-service
    image: product-service:1.0
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microdb?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  order-service:
    build:
      context: ./order-service
    image: order-service:1.0
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microdb?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  payment-service:
    build:
      context: ./payment-service
    image: payment-service:1.0
    container_name: payment-service
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microdb?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

networks:
  mynetwork:
    driver: bridge

